### ISSUE TITLE
Describing the current focus i.e. a screenshot of the webpage itself rather than the whole screen.

### ISSUE THREAD

**Issue by M3198** [AAClause/nvda-OpenAI#89]
Open AI issue.
Hi, I hope you are doing well. I was having an issue with your addon. Though it can describe a screenshot of the whole screen, what we also need is an option to describe the current focus i.e. just the current webpage, just like with the AI content describer addon.  Would you kindly add a keystroke for this as well. For example, rather than just describing the whole screen, just describing the current images on a specific webpage that is open, for example google images or any other website
To give an example.
If I type togg car into google images and press kcapslock E, it will not only give me a description of what's on the page, but it'll also describe the taskbar and other irrelevant icons. So what I would only want is a screenshot of only the images search results page talking about the togg car, not everything that's on my computer screen.
?
Best regards,
Muhammad.
Feel free to contact me at muhammed3198@gmail.com

**Comment by M3198** [comment]
Though I've tried your suggestion, it is only describing one image on the page. On the togg car example I've given, I want it to describe all 10 images that it sees. How do I do this?
Would you kindly add a keystroke to do this?
Best regards,
Muhammad

**Comment by M3198** [comment]
So I''m not sure whether you're receiving my email replies as I'm new to Github, but here was my question.
You said I could restrict the captured  navigation to the current window using object navigation. How do I do that?
Best regards,
Muhammad

**Comment by M3198** [comment]
I looked in the manual, specifically the section you mentioned, but can't find the command I need to use.
Since I'm using laptop keyboard layout, I pressed capslock backspace to move to the focus, then take a screenshot. Still same issue, I can't just focus just on the current page.
Please tell me exactly which specific command I need to use.
Best regards,
Muhammad.

**Comment by rperez030** [comment]
Hi Mohamed. With focus on the photo, or any element inside the page, press capslock +Shift +Up arrow to move focus to the parent element until you hear the name of the page you want to focus on. For example, here in Github it would be something like "Describing the current focus i.e. a screenshot of the webpage itself rather than the whole screen. · Issue #89 · aaclause/nvda-OpenAI  document". When you hear that announced, press Capslock  +O to grab a screenshot of that frame and open the chat interface. after that, you can ask a question and press CTRL +Enter, or press CTRL +Enter directly to generate a detailed description.

Does that help?

**Comment by M3198** [comment]
Thanks. Also, I think it would be very helpful if you also had an email address to show rather than just your contact channel on Github, for those who don't wish to use it.
